# Generated by Django 4.0.3 on 2022-03-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('core', '0004_pontosturisticos_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='endereco',
            field=models.ManyToManyField(to='endereco.endereco'),
        ),
    ]
