# Generated by Django 4.0.3 on 2022-03-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0001_initial'),
        ('core', '0005_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontosturisticos',
            name='endereco',
        ),
        migrations.AddField(
            model_name='pontosturisticos',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco'),
            preserve_default=False,
        ),
    ]
