# Generated by Django 4.0.3 on 2022-03-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('avaliacoes', '0002_rename_comentario_avaliacao_comentarios'),
        ('core', '0007_alter_pontosturisticos_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, null=True, to='avaliacoes.avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='comentarios.comentario'),
        ),
    ]
