# Generated by Django 4.0.3 on 2022-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('avaliacoes', '0004_rename_comentarios_avaliacao_comentario_and_more'),
        ('core', '0008_alter_pontosturisticos_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturisticos',
            name='avaliacoes',
            field=models.ManyToManyField(to='avaliacoes.avaliacao'),
        ),
        migrations.AlterField(
            model_name='pontosturisticos',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.comentario'),
        ),
    ]
