# Generated by Django 4.0.3 on 2022-03-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comentario',
            new_name='comentarios',
        ),
    ]
