# Generated by Django 4.0.3 on 2022-03-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_rename_comentario_avaliacao_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nota',
            new_name='notas',
        ),
    ]
