# Generated by Django 4.0.3 on 2022-03-09 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_rename_nota_avaliacao_notas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comentarios',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='notas',
            new_name='nota',
        ),
    ]
